apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokes
  labels:
    app: jokes
spec:
  replicas: 1  # You can change this to scale your app
  selector:
    matchLabels:
      app: jokes
  template:
    metadata:
      labels:
        app: jokes
    spec:
      containers:
      - name: jokes
        image: localhost:5000/m4rt1nn/joke-service:latest  # This is your image
        ports:
        - containerPort: 5000  # Expose port 80 (or whichever port your app listens on)
