apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokes-deployment
  namespace: joker
  labels:
    app: jokes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jokes-pod
  template:
    metadata:
      labels:
        app: jokes-pod
    spec:
      containers:
      - name: jokes-container
        image: registry:5000/m4rt1nn/joke-service:latest
        ports:
        - containerPort: 5000
