apiVersion: v1
kind: Service
metadata:
  name: jokes-service
  namespace: joker
spec:
  selector:
    app: jokes-pod
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 5000
  type: ClusterIP